name: Mod Build

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build project
        uses: ./gradlew remapJar